# Generated by Django 5.1.2 on 2025-05-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_variations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
