# Generated by Django 5.1.2 on 2025-05-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_address_line_2_order_floor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='orderproducts',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
