# Generated by Django 5.1.2 on 2025-05-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_table_alter_orderproduct_table_and_more'),
    ]

    operations = [
        # Migration này không làm gì cả, chỉ cập nhật trạng thái nội bộ của Django
    ]
