# Generated by Django 5.1.2 on 2025-05-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_floor_order_city_remove_order_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='floor',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
